require_relative './config/environment'
require 'sinatra/activerecord/rake'
# "rake -T" in terminal to list all rake tasks
desc "Start our app console"
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end
